In [2]:
import numpy as np

In [6]:
np.sum(np.array([[1,2,3,4,5], [1,2,3,4,5]]), axis=0)

array([ 2,  4,  6,  8, 10])

In [8]:
arr1 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

arr1/arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
ar1 = np.random.random([10, 2])
ar2 = np.random.random([2, 2])

np.linalg.norm(ar1[:, None, :] - ar2[None, :, :], axis=-1)

array([[0.70350303, 0.42227462],
       [0.05813829, 0.29540997],
       [0.54481945, 0.25658274],
       [0.16823561, 0.49096699],
       [0.67886542, 0.38028997],
       [0.30370829, 0.45514653],
       [0.64523794, 0.49417731],
       [0.74145209, 0.49454397],
       [0.04933952, 0.29130263],
       [0.6786159 , 0.43306444]])

In [17]:
np.linalg.norm(ar1[0]-ar2[1], axis=-1)

0.4222746176866059